# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Arceus.Code
PackageVersion: 1.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-07-13
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/amarreddy1432723-lang/autonomus_ai/releases/download/arceus-code-v1.0.0/Arceus-Code-1.0.0-Setup.exe
    InstallerSha256: 19E3FC1815BDF000013F165A793FEC276E5065DAEDEA5F77109F89B8D7989D75
ManifestType: installer
ManifestVersion: 1.6.0
