param(
  [string]$ArtifactsDir = ".\desktop\dist",
  [string]$ReleaseVersion = $env:RELEASE_VERSION,
  [string]$OwnerRepo = $env:GITHUB_REPOSITORY,
  [string]$OutputPath = "",
  [string]$Channel = "stable",
  [switch]$Signed
)

$ErrorActionPreference = "Stop"

if (-not $ReleaseVersion) {
  throw "ReleaseVersion is required. Pass -ReleaseVersion arceus-code-vX.Y.Z or set RELEASE_VERSION."
}

$tag = $ReleaseVersion -replace "^refs/tags/", ""
$artifactRoot = Resolve-Path $ArtifactsDir
if (-not $OutputPath) {
  $OutputPath = Join-Path $artifactRoot "release-download-env.ps1"
}

function Get-ReleaseKey([System.IO.FileInfo]$file) {
  $name = $file.Name
  if ($name -match "Setup\.exe$") { return "WINDOWS_X64_INSTALLER" }
  if ($name -match "arm64.*\.dmg$") { return "MACOS_ARM64_DMG" }
  if ($name -match "\.dmg$") { return "MACOS_X64_DMG" }
  if ($name -match "\.AppImage$") { return "LINUX_X64_APPIMAGE" }
  if ($name -match "\.deb$") { return "LINUX_X64_DEB" }
  if ($name -match "\.rpm$") { return "LINUX_X64_RPM" }
  return $null
}

function Get-ReleaseUrl([System.IO.FileInfo]$file) {
  if (-not $OwnerRepo) {
    return $file.FullName
  }
  $encodedName = [uri]::EscapeDataString($file.Name)
  return "https://github.com/$OwnerRepo/releases/download/$tag/$encodedName"
}

$files = Get-ChildItem -Path $artifactRoot -File -Recurse |
  Where-Object { $_.Extension -in ".exe", ".dmg", ".AppImage", ".deb", ".rpm" }

$lines = @(
  "# Generated by scripts/generate-release-download-env.ps1",
  "`$env:ARCEUS_RELEASE_VERSION=`"$tag`"",
  "`$env:ARCEUS_RELEASE_CHANNEL=`"$Channel`"",
  "`$env:ARCEUS_RELEASE_SIGNED=`"$($Signed.IsPresent.ToString().ToLowerInvariant())`"",
  "`$env:ARCEUS_RELEASE_NOTES_URL=`"https://github.com/$OwnerRepo/releases/tag/$tag`"",
  "`$env:ARCEUS_UPDATE_FEED_URL=`"https://github.com/$OwnerRepo/releases/latest`""
)

$records = @()
foreach ($file in $files) {
  $key = Get-ReleaseKey $file
  if (-not $key) {
    continue
  }
  $hash = (Get-FileHash -Algorithm SHA256 -Path $file.FullName).Hash.ToLowerInvariant()
  $url = Get-ReleaseUrl $file
  $lines += "`$env:ARCEUS_DOWNLOAD_${key}_URL=`"$url`""
  $lines += "`$env:ARCEUS_DOWNLOAD_${key}_SHA256=`"$hash`""
  $records += [pscustomobject]@{
    Key = $key
    File = $file.Name
    Sha256 = $hash
    Url = $url
  }
}

if (-not $records) {
  throw "No release artifacts found in $artifactRoot."
}

$outputDir = Split-Path -Parent $OutputPath
if ($outputDir) {
  New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
}
$lines | Set-Content -Path $OutputPath -Encoding UTF8

$jsonPath = [System.IO.Path]::ChangeExtension($OutputPath, ".json")
$records | ConvertTo-Json -Depth 4 | Set-Content -Path $jsonPath -Encoding UTF8

Write-Host "Generated release download env: $OutputPath"
Write-Host "Generated release artifact manifest: $jsonPath"
$records | Format-Table -AutoSize
