"""add_est_hours_columns_to_tasks

Revision ID: 5d3e4fdd4bfe
Revises: d6cb6eedf9b4
Create Date: 2026-06-28 13:02:02.965007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '5d3e4fdd4bfe'
down_revision: Union[str, None] = 'd6cb6eedf9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('est_hours_optimistic', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('est_hours_likely', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('est_hours_pessimistic', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('est_hours_pert', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('est_hours_std_dev', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'est_hours_std_dev')
    op.drop_column('tasks', 'est_hours_pert')
    op.drop_column('tasks', 'est_hours_pessimistic')
    op.drop_column('tasks', 'est_hours_likely')
    op.drop_column('tasks', 'est_hours_optimistic')
    # ### end Alembic commands ###
