"""phase6_database_alignment

Revision ID: d6cb6eedf9b4
Revises: e488b07988a5
Create Date: 2026-06-28 13:01:15.635039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'd6cb6eedf9b4'
down_revision: Union[str, None] = 'e488b07988a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('phase_number', sa.Integer(), nullable=True),
    sa.Column('milestone', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=True),
    sa.Column('lead_agent', sa.String(length=100), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('goal_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('schedule_type', sa.String(length=50), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=True),
    sa.Column('max_runs', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_payload', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('approval_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('approvals', sa.Column('task_id', sa.UUID(), nullable=True))
    op.add_column('approvals', sa.Column('requested_by_agent', sa.String(length=100), nullable=True))
    op.add_column('approvals', sa.Column('action_description', sa.Text(), nullable=True))
    op.add_column('approvals', sa.Column('action_payload', sa.JSON(), nullable=True))
    op.add_column('approvals', sa.Column('risk_level', sa.String(length=50), nullable=True))
    op.add_column('approvals', sa.Column('risk_reasoning', sa.Text(), nullable=True))
    op.add_column('approvals', sa.Column('if_approved', sa.Text(), nullable=True))
    op.add_column('approvals', sa.Column('if_rejected', sa.Text(), nullable=True))
    op.add_column('approvals', sa.Column('alternatives', sa.JSON(), nullable=True))
    op.add_column('approvals', sa.Column('decided_by', sa.String(length=50), nullable=True))
    op.add_column('approvals', sa.Column('user_response', sa.Text(), nullable=True))
    op.add_column('approvals', sa.Column('modified_payload', sa.JSON(), nullable=True))
    op.add_column('approvals', sa.Column('decision_reason', sa.Text(), nullable=True))
    op.add_column('approvals', sa.Column('timeout_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('approvals', sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('approvals', sa.Column('notification_ids', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'approvals', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.add_column('goals', sa.Column('parent_goal_id', sa.UUID(), nullable=True))
    op.add_column('goals', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('goals', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('goals', sa.Column('success_criteria', sa.JSON(), nullable=True))
    op.add_column('goals', sa.Column('constraints', sa.JSON(), nullable=True))
    op.add_column('goals', sa.Column('assumptions', sa.JSON(), nullable=True))
    op.add_column('goals', sa.Column('progress_pct', sa.Float(), nullable=True))
    op.add_column('goals', sa.Column('plan_version', sa.Integer(), nullable=True))
    op.add_column('goals', sa.Column('original_plan', sa.JSON(), nullable=True))
    op.add_column('goals', sa.Column('current_plan', sa.JSON(), nullable=True))
    op.add_column('goals', sa.Column('plan_change_log', sa.JSON(), nullable=True))
    op.add_column('goals', sa.Column('estimated_hours_total', sa.Float(), nullable=True))
    op.add_column('goals', sa.Column('actual_hours_total', sa.Float(), nullable=True))
    op.add_column('goals', sa.Column('estimation_accuracy_pct', sa.Float(), nullable=True))
    op.add_column('goals', sa.Column('reflection_summary', sa.Text(), nullable=True))
    op.add_column('goals', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'goals', 'goals', ['parent_goal_id'], ['id'], ondelete='SET NULL')
    op.add_column('memories', sa.Column('memory_type', sa.String(length=100), nullable=True))
    op.add_column('memories', sa.Column('content_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.add_column('memories', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('memories', sa.Column('source_session_id', sa.UUID(), nullable=True))
    op.add_column('memories', sa.Column('source_url', sa.String(length=500), nullable=True))
    op.add_column('memories', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('memories', sa.Column('access_count', sa.Integer(), nullable=True))
    op.add_column('memories', sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('memories', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('memories', sa.Column('related_memory_ids', sa.JSON(), nullable=True))
    op.add_column('memories', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('memories', sa.Column('is_superseded', sa.Boolean(), nullable=True))
    op.add_column('memories', sa.Column('superseded_by', sa.UUID(), nullable=True))
    op.add_column('memories', sa.Column('compressed_from', sa.JSON(), nullable=True))
    op.add_column('memories', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'memories', 'memories', ['superseded_by'], ['id'])
    op.add_column('task_executions', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('task_executions', sa.Column('attempt_number', sa.Integer(), nullable=True))
    op.add_column('task_executions', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('task_executions', sa.Column('model_used', sa.String(length=100), nullable=True))
    op.add_column('task_executions', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('task_executions', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('task_executions', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('task_executions', sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('task_executions', sa.Column('tool_calls', sa.JSON(), nullable=True))
    op.add_column('task_executions', sa.Column('output_text', sa.Text(), nullable=True))
    op.add_column('task_executions', sa.Column('output_data', sa.JSON(), nullable=True))
    op.add_column('task_executions', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('task_executions', sa.Column('error_type', sa.String(length=100), nullable=True))
    op.add_column('task_executions', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.add_column('task_executions', sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('task_executions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'task_executions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('project_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('parent_task_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('actual_hours', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('is_critical_path', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('float_hours', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('earliest_start_day', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('earliest_finish_day', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('latest_start_day', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('latest_finish_day', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('success_criteria', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('execution_result', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('quality_score', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('max_retries', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_profiles', sa.Column('communication_style', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('work_patterns', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('decision_style', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('domain_expertise', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('tool_preferences', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('estimation_biases', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('feedback_patterns', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('model_version', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('model_confidence', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('auth_provider_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('locale', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active_at')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'locale')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'auth_provider_id')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'name')
    op.drop_column('user_profiles', 'model_confidence')
    op.drop_column('user_profiles', 'model_version')
    op.drop_column('user_profiles', 'feedback_patterns')
    op.drop_column('user_profiles', 'estimation_biases')
    op.drop_column('user_profiles', 'tool_preferences')
    op.drop_column('user_profiles', 'domain_expertise')
    op.drop_column('user_profiles', 'decision_style')
    op.drop_column('user_profiles', 'work_patterns')
    op.drop_column('user_profiles', 'communication_style')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'started_at')
    op.drop_column('tasks', 'max_retries')
    op.drop_column('tasks', 'retry_count')
    op.drop_column('tasks', 'quality_score')
    op.drop_column('tasks', 'execution_result')
    op.drop_column('tasks', 'success_criteria')
    op.drop_column('tasks', 'latest_finish_day')
    op.drop_column('tasks', 'latest_start_day')
    op.drop_column('tasks', 'earliest_finish_day')
    op.drop_column('tasks', 'earliest_start_day')
    op.drop_column('tasks', 'float_hours')
    op.drop_column('tasks', 'is_critical_path')
    op.drop_column('tasks', 'actual_hours')
    op.drop_column('tasks', 'parent_task_id')
    op.drop_column('tasks', 'project_id')
    op.drop_constraint(None, 'task_executions', type_='foreignkey')
    op.drop_column('task_executions', 'completed_at')
    op.drop_column('task_executions', 'started_at')
    op.drop_column('task_executions', 'duration_ms')
    op.drop_column('task_executions', 'error_type')
    op.drop_column('task_executions', 'error_message')
    op.drop_column('task_executions', 'output_data')
    op.drop_column('task_executions', 'output_text')
    op.drop_column('task_executions', 'tool_calls')
    op.drop_column('task_executions', 'cost_usd')
    op.drop_column('task_executions', 'total_tokens')
    op.drop_column('task_executions', 'completion_tokens')
    op.drop_column('task_executions', 'prompt_tokens')
    op.drop_column('task_executions', 'model_used')
    op.drop_column('task_executions', 'status')
    op.drop_column('task_executions', 'attempt_number')
    op.drop_column('task_executions', 'user_id')
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.drop_column('memories', 'expires_at')
    op.drop_column('memories', 'compressed_from')
    op.drop_column('memories', 'superseded_by')
    op.drop_column('memories', 'is_superseded')
    op.drop_column('memories', 'is_archived')
    op.drop_column('memories', 'related_memory_ids')
    op.drop_column('memories', 'tags')
    op.drop_column('memories', 'last_accessed_at')
    op.drop_column('memories', 'access_count')
    op.drop_column('memories', 'confidence')
    op.drop_column('memories', 'source_url')
    op.drop_column('memories', 'source_session_id')
    op.drop_column('memories', 'source')
    op.drop_column('memories', 'content_vector')
    op.drop_column('memories', 'memory_type')
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_column('goals', 'completed_at')
    op.drop_column('goals', 'reflection_summary')
    op.drop_column('goals', 'estimation_accuracy_pct')
    op.drop_column('goals', 'actual_hours_total')
    op.drop_column('goals', 'estimated_hours_total')
    op.drop_column('goals', 'plan_change_log')
    op.drop_column('goals', 'current_plan')
    op.drop_column('goals', 'original_plan')
    op.drop_column('goals', 'plan_version')
    op.drop_column('goals', 'progress_pct')
    op.drop_column('goals', 'assumptions')
    op.drop_column('goals', 'constraints')
    op.drop_column('goals', 'success_criteria')
    op.drop_column('goals', 'priority')
    op.drop_column('goals', 'category')
    op.drop_column('goals', 'parent_goal_id')
    op.drop_constraint(None, 'approvals', type_='foreignkey')
    op.drop_column('approvals', 'notification_ids')
    op.drop_column('approvals', 'decided_at')
    op.drop_column('approvals', 'timeout_at')
    op.drop_column('approvals', 'decision_reason')
    op.drop_column('approvals', 'modified_payload')
    op.drop_column('approvals', 'user_response')
    op.drop_column('approvals', 'decided_by')
    op.drop_column('approvals', 'alternatives')
    op.drop_column('approvals', 'if_rejected')
    op.drop_column('approvals', 'if_approved')
    op.drop_column('approvals', 'risk_reasoning')
    op.drop_column('approvals', 'risk_level')
    op.drop_column('approvals', 'action_payload')
    op.drop_column('approvals', 'action_description')
    op.drop_column('approvals', 'requested_by_agent')
    op.drop_column('approvals', 'task_id')
    op.drop_table('notifications')
    op.drop_table('schedules')
    op.drop_table('projects')
    op.drop_table('integrations')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
